language: node_js
sudo: required
dist: trusty

node_js:
  - "9.8"

python:
  - "2.7"

env:
  CIKIT_BRANCH: master
  ANSIBLE_VERBOSITY: 2

services:
  - docker

install:
  - sudo pip install ansible==2.8.6
  - curl -LSs https://raw.githubusercontent.com/BR0kEN-/cikit/master/install.sh | sudo bash -s -- --no-requirements-check
  - cd /usr/local/share/cikit/
  - sudo git pull origin ${CIKIT_BRANCH} --recurse-submodules
  - cd ./matrix/roles/api/files/cikit-rest-api/
  - sudo git pull origin ${TRAVIS_BRANCH} --recurse-submodules

script:
  - sudo bash start.sh test
after_script:
  - cd docroot && ls -la && npm run test:coverage:coveralls

notifications:
  slack: cikit:aT0Y9ZQggfbkLoxONJ7Hg1OO
